### ISSUE TITLE
I am getting not ok - timeout

### ISSUE THREAD

**Issue by pke** [testiumjs/babel-tap#3]
using `babel-tap src/specs/index.js`

index.js

```
import {test} from 'babel-tap'

test('A passing test', (assert) => {
  assert.pass('This test will pass.')
  assert.end()
})

test('Assertions with tape.', (assert) => {
  const expected = 'something to test'
  const actual = 'sonething to test'

  assert.equal(actual, expected,
    'Given two mismatched values, .equal() should produce a nice bug report')
  assert.end()
})
```

**Comment by hybrist** [comment]
Thanks for the feedback! With the latest version of `babel-tap` (4.0.0) I get the following:

```
> ./cli.js test.timeout.js 
test.timeout.js ....................................... 1/2 2s
  Assertions with tape.
  not ok Given two mismatched values, .equal() should produce a nice bug report
    +++ found                                                          
    --- wanted                                                         
    -something to test                                                 
    +sonething to test                                                 
    compare: ===
    at:
      file: test.timeout.js
      line: 14
      column: 10
    source: |
      assert.end()
    stack: >
      test.timeout.js:12:10

      Test.test (node_modules/tap/lib/test.js:399:17)

      Object.<anonymous> (test.timeout.js:8:1)

      normalLoader (node_modules/babel-core/lib/api/register/node.js:199:5)

      Object.require.extensions.(anonymous function) [as .js]
      (node_modules/babel-core/lib/api/register/node.js:216:7)

      Object.<anonymous> (node_modules/babel/lib/_babel-node.js:144:25)

      node.js:963:3

total ................................................. 1/2


  1 passing (2s)
  1 failing
```

I'm running node 4.2 if that makes a difference. Could you create a PR with the failing test to make sure it's reproducible?

**Comment by pke** [comment]
I am on node 0.12.2 and even with 4.0.0 the output is the same:

```
babel-tap@4.0.0 node_modules\babel-tap
$ node --version
v0.12.2

$ babel-tap src/specs/index.js
TAP version 13
    # Subtest: src/specs/index.js
    1..0


    not ok - timeout
```

**Comment by hybrist** [comment]
Without a test case it's not really possible to reproduce this. Maybe it's a windows issue (seeing a `\` separator in your output)..? Happy to look into it if you can create a PR with a failing test. Without it I can't really tell what's going on. :)

**Comment by ffigiel** [comment]
I sort of reproduced the problem. It doesn't timeout (Banana PI doesn't count, right?), but it does take a _lot_ of time to finish. Node 4.4.0, deps up-to-date.

Here's a test

```
$ cat test/dummy.js
import tap from 'babel-tap'

tap.equal(2 + 2, 4, 'Math test')
```

It takes whooping 6 seconds to run this test:

<pre>
$ node_modules/.bin/babel-tap test/dummy.js
test/dummy.js ......................................... 1/1 <b>6s</b>
total ................................................. 1/1
  1 passing <b>(6s)</b>
  ok
</pre>

Now compare this to plain tap tests:

```
$ cat test/dummy.js
var tap = require('babel-tap');

tap.equal(2 + 2, 4, 'Math test')
```

It's 20 times faster! :confused: 

<pre>
$ node_modules/.bin/tap test/dummy.js
test/dummy.js ......................................... 1/1
total ................................................. 1/1
  1 passing <b>(325.475ms)</b>
  ok
</pre>

**Comment by ffigiel** [comment]
Seems like babel-cli is the bottleneck here. How can we speed it up?

<pre>
$ time node_modules/.bin/babel-node test/dummy.js
TAP version 13
    # Subtest: Dummy test
    ok 1 - Math test
    1..1
ok 1 - Dummy test # time=<b>12.708ms</b>
1..1
# time=<b>37.019ms</b>
<b>real    0m5.519s</b>
user    0m5.104s
sys     0m0.576s
</pre>

**Comment by ffigiel** [comment]
Comments in this [SO question](http://stackoverflow.com/questions/35244962/babel-cli-is-extremely-slow) helped me speed up babael-cli. It's still rather slow, as processing each file takes 1 second.

Is it possible to process all files simultaneously? Currently, if there are 15 test files, it will take ~20s to run the tests

**Comment by hybrist** [comment]
I'm afraid that's part of how `tap` works in general (as in: the npm package `tap`). You could try [proposing parallel execution there](https://github.com/tapjs/node-tap/issues). `babel-tap` is just a very thin wrapper around `tap` itself.

**Comment by kapooostin** [comment]
Now `tap` has an option `--no-timeout` but `babel-tap` seems to ignore it.

**Comment by hybrist** [comment]
@kapooostin Can you find out why? `babel-tap` just [forwards directly to `tap` itself](https://github.com/jkrems/babel-tap/blob/master/cli.js#L4), it doesn't do any argument parsing.
